name: pp-dev-api

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: whoami
      - run: pwd
      - run: ls -la
      - run: echo how are you
      - run: |
          cd ~/home/ubuntu/chagalchagal
          pwd
          git pull
      - run: sudo pm2 restart 0
