name: usman server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: whoami
      - run: |
          cd /home/ubuntu/chagalchagal
          pwd
          git pull
      - run: sudo node index.js
